name: Sync and Build

on:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly on the 1st at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch latest tags from upstream
        run: git fetch upstream --tags

      - name: Checkout latest release tag
        id: checkout_latest
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          git checkout $LATEST_TAG

      - name: Merge latest release into main
        run: |
          git checkout main
          git merge ${{ env.LATEST_TAG }} --strategy-option theirs

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/perplexica:latest -f Dockerfile.combined .
          docker push ghcr.io/${{ github.repository_owner }}/perplexica:latest