name: Sync and Build

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of each month
  workflow_dispatch: # Allows for manual triggering of the workflow

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Fetch latest release tag
        id: get_latest_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/ItzCrazyKns/Perplexica/releases/latest | jq -r .tag_name)
          echo "::set-output name=tag::$LATEST_TAG"

      - name: Add remote upstream
        run: git remote add upstream https://github.com/ItzCrazyKns/Perplexica.git

      - name: Fetch upstream latest release
        run: git fetch upstream refs/tags/${{ steps.get_latest_release.outputs.tag }}

      - name: Merge upstream latest release
        run: git merge --allow-unrelated-histories --no-commit --strategy=ours upstream/${{ steps.get_latest_release.outputs.tag }}
      
      - name: Restore added files
        run: git restore --source=HEAD@{1} -- Dockerfile.combined entrypoint.sh

      - name: Commit changes
        run: |
          git commit -m "Sync with latest release from upstream"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.combined
          push: true
          tags: ghcr.io/ds-sebastian/perplexica:latest
          
      - name: Push changes
        run: git push origin main
